name: lecsum
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.10.8

  - pip:
    - scipy==1.9.3
    - django==4.1.4
    - django-cors-headers==3.13.0
    - djangorestframework==3.14.0
    - editdistance==0.6.1
    - reportlab==3.6.12
    - pypdf2==2.12.1
    - openai==0.25.0
    - networkx==2.8.8
    - nltk==3.8
    - fpdf==1.7.2
